version: "3"

services:
  hosseli:
    build:
      context: ./
      dockerfile: Dockerfile
    image: alanendev/hosseli
    ports:
      - "3000:3000"
    environment:
      - DIGITRANSIT_SUBSCRIPTION_KEY=<key>
